// --------------------------------------------------------------------------------------
// TOML type provider - runtime document type
// --------------------------------------------------------------------------------------

namespace FSharp.Data.Runtime.BaseTypes

open System.ComponentModel
open System.IO
open FSharp.Data
open FSharp.Data.Runtime.BaseTypes

#nowarn "10001"

/// <summary>Underlying representation of types generated by TomlProvider</summary>
[<StructuredFormatDisplay("{JsonValue}")>]
type TomlDocument =

    private
        { Toml: TomlValue
          BackingJson: IJsonDocument }

    interface IJsonDocument with
        member x.JsonValue = x.BackingJson.JsonValue
        member x.Path() = x.BackingJson.Path()

        member x.CreateNew(value, pathIncrement) =
            { Toml = x.Toml
              BackingJson = x.BackingJson.CreateNew(value, pathIncrement) }

    /// The underlying TOML value
    member x.TomlValue = x.Toml

    /// The JSON value backing this document (used by the type provider runtime)
    member x.JsonValue = x.BackingJson.JsonValue

    /// <exclude />
    [<EditorBrowsableAttribute(EditorBrowsableState.Never)>]
    [<CompilerMessageAttribute("This method is intended for use in generated code only.",
                               10001,
                               IsHidden = true,
                               IsError = false)>]
    override x.ToString() = x.TomlValue.ToString()

    /// <exclude />
    [<EditorBrowsableAttribute(EditorBrowsableState.Never)>]
    [<CompilerMessageAttribute("This method is intended for use in generated code only.",
                               10001,
                               IsHidden = true,
                               IsError = false)>]
    static member Create(tomlValue: TomlValue, path: string) : IJsonDocument =
        let jsonValue = tomlValue.ToJsonValue()
        let backing = JsonDocument.Create(jsonValue, path)

        { Toml = tomlValue
          BackingJson = backing }

    /// <exclude />
    [<EditorBrowsableAttribute(EditorBrowsableState.Never)>]
    [<CompilerMessageAttribute("This method is intended for use in generated code only.",
                               10001,
                               IsHidden = true,
                               IsError = false)>]
    static member Create(reader: TextReader) : IJsonDocument =
        use reader = reader
        let text = reader.ReadToEnd()
        let tomlValue = TomlValue.Parse(text)
        TomlDocument.Create(tomlValue, "")
