// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.Json.Core")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("5.0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FSharp.Data.Json.Core"

    [<Literal>]
    let AssemblyProduct = "FSharp.Data"

    [<Literal>]
    let AssemblyDescription = "Library of F# type providers and data access tools"

    [<Literal>]
    let AssemblyVersion = "5.0.1.0"

    [<Literal>]
    let AssemblyFileVersion = "5.0.1.0"
