// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharp.Data.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("3.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0.0")>]
[<assembly:InternalsVisibleToAttribute("FSharp.Data.DesignTime.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data"
    let [<Literal>] AssemblyDescription = "Library of F# type providers and data access tools"
    let [<Literal>] AssemblyVersion = "3.0.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0.0"
