// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.Runtime.Utilities")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("6.6.0.0")>]
[<assembly: AssemblyFileVersionAttribute("6.6.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FSharp.Data.Runtime.Utilities"

    [<Literal>]
    let AssemblyProduct = "FSharp.Data"

    [<Literal>]
    let AssemblyDescription = "Library of F# type providers and data access tools"

    [<Literal>]
    let AssemblyVersion = "6.6.0.0"

    [<Literal>]
    let AssemblyFileVersion = "6.6.0.0"
