// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.Xml.Core")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("5.0.3.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.3.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.Xml.Core"
    let [<Literal>] AssemblyProduct = "FSharp.Data"
    let [<Literal>] AssemblyDescription = "Library of F# type providers and data access tools"
    let [<Literal>] AssemblyVersion = "5.0.3.0"
    let [<Literal>] AssemblyFileVersion = "5.0.3.0"
