// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("2.4.3.259")>]
[<assembly: AssemblyFileVersionAttribute("2.4.3.259")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data"
    let [<Literal>] AssemblyProduct = "FSharp.Data"
    let [<Literal>] AssemblyDescription = "Library of F# type providers and data access tools"
    let [<Literal>] AssemblyVersion = "2.4.3.259"
    let [<Literal>] AssemblyFileVersion = "2.4.3.259"
