// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data")>]
[<assembly: AssemblyDescriptionAttribute("Library of F# type providers and data access tools")>]
[<assembly: AssemblyVersionAttribute("4.2.8.0")>]
[<assembly: AssemblyFileVersionAttribute("4.2.8.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data"
    let [<Literal>] AssemblyDescription = "Library of F# type providers and data access tools"
    let [<Literal>] AssemblyVersion = "4.2.8.0"
    let [<Literal>] AssemblyFileVersion = "4.2.8.0"
